version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    directory: "/services/broker"
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    directory: "/services/compiler"
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    directory: "/services/judge"
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    directory: "/services/course"
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    directory: "/services/account"
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    directory: "/services/progression"
    schedule:
      interval: daily
    target-branch: main
