version: 2
updates:
  - package-ecosystem: npm
    directory: "/web/ui"
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: "/cmd/api"
    schedule:
      interval: weekly
