version: '3'

services:

  broker:
    container_name: broker
    build:
      context: ./broker
      dockerfile: ./broker.dockerfile
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ENVIRONMENT: development
      # PRODUCTION_USER_ENDPOINT:

  user:
    container_name: user
    build:
      context: ./user
      dockerfile: ./user.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ENVIRONMENT: development
      # PRODUCTION_DB_URL:

  postgres:
    container_name: db-users
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/